import { mkdirSync, writeFileSync } from 'node:fs'
import { DEFAULT_ASSISTANT_LABELS } from '@4djs/assistant'

const fr: Record<string, string> = {
  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.saving': 'Enregistrement…',
  'common.dismiss': 'Fermer',
  'common.loading': 'Chargement…',
  'common.error': 'Erreur',
  'common.result': 'Résultat',
  'common.edit': 'Modifier',
  'common.preview': 'Aperçu',
  'common.regenerate': 'Régénérer',
  'common.tryAgain': 'Réessayer',
  'header.title': 'Assistant',
  'message.assistantRole': 'Assistant',
  'message.thinking': "L'assistant réfléchit",
  'message.copyPrompt': 'Copier le prompt',
  'message.copyPromptSuccess': 'Prompt copié',
  'composer.placeholder': 'Posez une question…',
  'composer.placeholderDisabled': 'LLM non configuré — le chat est désactivé',
  'composer.messageAria': 'Message de chat',
  'composer.send': 'Envoyer',
  'composer.stop': 'Arrêter',
  'composer.hint': 'Entrée pour envoyer · Maj+Entrée pour une nouvelle ligne',
  'composer.llmSettings': 'Paramètres LLM',
  'composer.generateSuggestions': 'Générer des suggestions',
  'composer.clearConversation': 'Effacer la conversation',
  'commandMenu.ariaLabel': 'Commandes du compositeur',
  'commandMenu.header': 'Commandes',
  'commands.clear.description': 'Effacer la conversation en cours',
  'commands.clear.noArgsError': "La commande /clear n'accepte pas d'arguments.",
  'commands.clear.waitForFinishError': "Attendez la fin de la réponse avant d'effacer.",
  'commands.compact.description': 'Compacter le contexte de la conversation',
  'commands.compact.noArgsError': "La commande /compact n'accepte pas d'arguments.",
  'commands.compact.waitForFinishError': 'Attendez la fin de la réponse avant de compacter.',
  'commands.compact.nothingToCompact': 'Rien à compacter pour le moment.',
  'commands.compact.llmRequired':
    'Connectez un LLM dans les paramètres pour résumer le contexte précédent.',
  'message.compactedContext': 'Contexte compacté',
  'compact.loading': 'Compactage du contexte…',
  'compact.showMore': 'Afficher tout le résumé',
  'compact.showLess': 'Afficher moins',
  'commands.unknown': 'Commande inconnue : /{name}',
  'commands.failed': 'Échec de la commande',
  'llmSetup.notConnected': 'LLM non connecté.',
  'llmSetup.addProviderBeforeLink': 'Ajoutez un fournisseur cloud ou local dans',
  'llmSetup.settingsLink': 'Paramètres LLM',
  'llmSetup.connectTitle': 'Connecter un LLM',
  'llmSetup.connectDescription': 'Point de terminaison compatible OpenAI — cloud ou local',
  'llmSetup.configure': 'Configurer',
  'llmSettings.title': 'Paramètres LLM',
  'llmSettings.ariaLabel': 'Paramètres LLM',
  'llmSettings.testConnection': 'Tester la connexion',
  'llmSettings.resetAllSettings': 'Réinitialiser tous les paramètres',
  'llmSettings.close': 'Fermer les paramètres LLM',
  'llmSettings.baseUrl': 'URL de base',
  'llmSettings.apiKey': 'Clé API',
  'llmSettings.model': 'Modèle',
  'llmSettings.advanced': 'Avancé',
  'llmSettings.modelList': 'Liste des modèles',
  'llmSettings.baseUrlPlaceholder': 'https://api.openai.com/v1',
  'llmSettings.apiKeyPlaceholder': 'sk-…',
  'llmSettings.apiKeyConfiguredPlaceholder': 'Configurée — laisser vide pour conserver',
  'llmSettings.showApiKey': 'Afficher la clé API',
  'llmSettings.hideApiKey': 'Masquer la clé API',
  'llmSettings.copyApiKey': 'Copier la clé API',
  'llmSettings.copyApiKeySuccess': 'Clé API copiée',
  'llmSettings.modelPlaceholder': 'gpt-4o-mini',
  'llmSettings.modelListPlaceholder': 'Optionnel — séparés par des virgules',
  'llmSettings.connected': 'Connecté · {model}',
  'llmSettings.resetAll': 'Tout réinitialiser',
  'llmSettings.failedToLoad': 'Échec du chargement des paramètres LLM',
  'llmSettings.failedToSave': "Échec de l'enregistrement des paramètres LLM",
  'llmSettings.failedToReset': 'Échec de la réinitialisation des paramètres LLM',
  'systemPrompt.label': 'Invite système',
  'systemPrompt.defaultTag': 'Par défaut',
  'systemPrompt.viewAria': "Vue de l'invite système",
  'systemPrompt.resetAria': "Réinitialiser l'invite système",
  'systemPrompt.resetTitle': 'Réinitialiser par défaut',
  'systemPrompt.placeholder': 'Optionnel — remplace la valeur par défaut',
  'systemPrompt.editorAria': "Éditeur d'invite système",
  'systemPrompt.previewAria': "Aperçu de l'invite système",
  'modelSelector.label': 'Modèle',
  'modelSelector.modelAria': 'Modèle LLM',
  'modelSelector.loadingModels': 'Chargement des modèles…',
  'modelSelector.searchModels': 'Rechercher des modèles…',
  'modelSelector.suggestionsAria': 'Suggestions de modèles',
  'modelSelector.custom': 'Personnalisé',
  'suggestions.ariaLabel': 'Suggestions de prompts',
  'suggestions.title': 'Suggestions',
  'suggestions.generate': 'Générer',
  'suggestions.close': 'Fermer les suggestions',
  'suggestions.loading': 'Chargement des suggestions',
  'suggestions.failedToLoad': 'Échec du chargement des suggestions',
  'emptyState.eyebrow': 'Assistant IA',
  'emptyState.generateSuggestions': 'Générer des suggestions',
  'emptyState.generateSuggestionsHint': 'Prompts adaptés à votre catalogue en direct',
  'emptyState.generating': 'Génération des suggestions',
  'emptyState.suggestedForYou': 'Suggéré pour vous',
  'emptyState.quickStarts': 'Démarrages rapides',
  'emptyState.capabilities.catalog': 'Catalogue',
  'emptyState.capabilities.query': 'Requête',
  'emptyState.capabilities.mutate': 'Modification',
  'activity.trace': 'Trace',
  'activity.copyTrace': 'Copier la trace',
  'activity.copyTraceSuccess': 'Trace copiée',
  'activity.live': 'En direct',
  'activity.arguments': 'Arguments',
  'activity.running': 'Exécution…',
  'activity.widgetInResponse': 'Widget affiché dans la réponse ci-dessus',
  'activity.steps.waitingConfirmation': 'En attente de confirmation…',
  'activity.steps.waitingChoice': 'En attente de votre choix…',
  'activity.steps.suggestingReplies': 'Suggestion de réponses…',
  'activity.steps.running': 'Exécution de {name}…',
  'activity.steps.failed': 'Échec de {name}',
  'activity.steps.confirmationAnswered': 'Confirmation reçue',
  'activity.steps.choiceSubmitted': 'Choix envoyé',
  'activity.steps.replySuggestionsShown': 'Suggestions de réponses affichées',
  'activity.steps.ran': '{name} exécuté',
  'interactive.chooseOptions': 'Choisir des options',
  'interactive.chooseOne': 'Choisir une option',
  'interactive.choicesKeyboardHint': '1-9 · Entrée · Échap',
  'interactive.confirmationKeyboardHint': 'Entrée · Échap',
  'interactive.confirm': 'Confirmer',
  'interactive.confirmDeletion': 'Confirmer la suppression',
  'interactive.invalidArgs': "Arguments d'outil interactif invalides",
  'replySuggestions.legend': 'Réponses suggérées',
  'replySuggestions.pickHint': 'pour choisir · ou saisir ci-dessous',
  'replySuggestions.badges.model': 'Modèle',
  'replySuggestions.badges.status': 'Statut',
  'replySuggestions.badges.tools': 'Outils',
  'replySuggestions.badges.dataclass': 'Dataclass',
  'replySuggestions.badges.filter': 'Filtre',
  'scroll.toBottom': 'Défiler vers le bas',
  'errors.network.title': 'Connexion perdue',
  'errors.network.hintChat':
    'Vérifiez votre réseau ou le point de terminaison LLM, puis réessayez.',
  'errors.network.hintSuggestions': 'Vérifiez votre connexion et les paramètres LLM.',
  'errors.auth.title': "Échec de l'authentification",
  'errors.auth.hint': 'Vérifiez votre clé API ou vos identifiants dans les paramètres LLM.',
  'errors.timeout.title': "Délai d'attente dépassé",
  'errors.timeout.hint': 'Le modèle a mis trop de temps à répondre. Réessayez dans un instant.',
  'errors.rateLimit.title': 'Limite de débit atteinte',
  'errors.rateLimit.hint': "Attendez quelques secondes avant d'envoyer une autre requête.",
  'errors.unknown.titleChat': "Une erreur s'est produite",
  'errors.unknown.titleSuggestions': 'Impossible de charger les suggestions',
  'errors.unknown.hintChat': 'Réessayez ou vérifiez vos paramètres LLM.',
  'errors.unknown.hintSuggestions': 'Régénérez ou vérifiez la configuration LLM.',
}

const es: Record<string, string> = {
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.saving': 'Guardando…',
  'common.dismiss': 'Cerrar',
  'common.loading': 'Cargando…',
  'common.error': 'Error',
  'common.result': 'Resultado',
  'common.edit': 'Editar',
  'common.preview': 'Vista previa',
  'common.regenerate': 'Regenerar',
  'common.tryAgain': 'Reintentar',
  'header.title': 'Asistente',
  'message.assistantRole': 'Asistente',
  'message.thinking': 'El asistente está pensando',
  'message.copyPrompt': 'Copiar el prompt',
  'message.copyPromptSuccess': 'Prompt copiado',
  'composer.placeholder': 'Haz una pregunta…',
  'composer.placeholderDisabled': 'LLM no configurado — el chat está desactivado',
  'composer.messageAria': 'Mensaje del chat',
  'composer.send': 'Enviar',
  'composer.stop': 'Detener',
  'composer.hint': 'Enter para enviar · Mayús+Enter para nueva línea',
  'composer.llmSettings': 'Ajustes del LLM',
  'composer.generateSuggestions': 'Generar sugerencias',
  'composer.clearConversation': 'Borrar conversación',
  'commandMenu.ariaLabel': 'Comandos del compositor',
  'commandMenu.header': 'Comandos',
  'commands.clear.description': 'Borrar la conversación actual',
  'commands.clear.noArgsError': 'El comando /clear no acepta argumentos.',
  'commands.clear.waitForFinishError': 'Espera a que el asistente termine antes de borrar.',
  'commands.compact.description': 'Compactar el contexto de la conversación',
  'commands.compact.noArgsError': 'El comando /compact no acepta argumentos.',
  'commands.compact.waitForFinishError': 'Espera a que el asistente termine antes de compactar.',
  'commands.compact.nothingToCompact': 'No hay nada que compactar todavía.',
  'commands.compact.llmRequired':
    'Conecta un LLM en los ajustes para resumir el contexto anterior.',
  'message.compactedContext': 'Contexto compactado',
  'compact.loading': 'Compactando contexto…',
  'compact.showMore': 'Mostrar resumen completo',
  'compact.showLess': 'Mostrar menos',
  'commands.unknown': 'Comando desconocido: /{name}',
  'commands.failed': 'Error en el comando',
  'llmSetup.notConnected': 'LLM no conectado.',
  'llmSetup.addProviderBeforeLink': 'Añade un proveedor en la nube o local en',
  'llmSetup.settingsLink': 'Ajustes del LLM',
  'llmSetup.connectTitle': 'Conectar un LLM',
  'llmSetup.connectDescription': 'Endpoint compatible con OpenAI — en la nube o local',
  'llmSetup.configure': 'Configurar',
  'llmSettings.title': 'Ajustes del LLM',
  'llmSettings.ariaLabel': 'Ajustes del LLM',
  'llmSettings.testConnection': 'Probar conexión',
  'llmSettings.resetAllSettings': 'Restablecer todos los ajustes',
  'llmSettings.close': 'Cerrar ajustes del LLM',
  'llmSettings.baseUrl': 'URL base',
  'llmSettings.apiKey': 'Clave API',
  'llmSettings.model': 'Modelo',
  'llmSettings.advanced': 'Avanzado',
  'llmSettings.modelList': 'Lista de modelos',
  'llmSettings.baseUrlPlaceholder': 'https://api.openai.com/v1',
  'llmSettings.apiKeyPlaceholder': 'sk-…',
  'llmSettings.apiKeyConfiguredPlaceholder': 'Configurada — dejar en blanco para mantener',
  'llmSettings.showApiKey': 'Mostrar clave API',
  'llmSettings.hideApiKey': 'Ocultar clave API',
  'llmSettings.copyApiKey': 'Copiar clave API',
  'llmSettings.copyApiKeySuccess': 'Clave API copiada',
  'llmSettings.modelPlaceholder': 'gpt-4o-mini',
  'llmSettings.modelListPlaceholder': 'Opcional — separados por comas',
  'llmSettings.connected': 'Conectado · {model}',
  'llmSettings.resetAll': 'Restablecer todo',
  'llmSettings.failedToLoad': 'No se pudieron cargar los ajustes del LLM',
  'llmSettings.failedToSave': 'No se pudieron guardar los ajustes del LLM',
  'llmSettings.failedToReset': 'No se pudieron restablecer los ajustes del LLM',
  'systemPrompt.label': 'Prompt del sistema',
  'systemPrompt.defaultTag': 'Predeterminado',
  'systemPrompt.viewAria': 'Vista del prompt del sistema',
  'systemPrompt.resetAria': 'Restablecer prompt del sistema',
  'systemPrompt.resetTitle': 'Restablecer por defecto',
  'systemPrompt.placeholder': 'Opcional — reemplaza el valor predeterminado',
  'systemPrompt.editorAria': 'Editor del prompt del sistema',
  'systemPrompt.previewAria': 'Vista previa del prompt del sistema',
  'modelSelector.label': 'Modelo',
  'modelSelector.modelAria': 'Modelo LLM',
  'modelSelector.loadingModels': 'Cargando modelos…',
  'modelSelector.searchModels': 'Buscar modelos…',
  'modelSelector.suggestionsAria': 'Sugerencias de modelos',
  'modelSelector.custom': 'Personalizado',
  'suggestions.ariaLabel': 'Sugerencias de prompts',
  'suggestions.title': 'Sugerencias',
  'suggestions.generate': 'Generar',
  'suggestions.close': 'Cerrar sugerencias',
  'suggestions.loading': 'Cargando sugerencias',
  'suggestions.failedToLoad': 'No se pudieron cargar las sugerencias',
  'emptyState.eyebrow': 'Asistente IA',
  'emptyState.generateSuggestions': 'Generar sugerencias',
  'emptyState.generateSuggestionsHint': 'Prompts adaptados a tu catálogo en vivo',
  'emptyState.generating': 'Generando sugerencias',
  'emptyState.suggestedForYou': 'Sugerido para ti',
  'emptyState.quickStarts': 'Inicios rápidos',
  'emptyState.capabilities.catalog': 'Catálogo',
  'emptyState.capabilities.query': 'Consulta',
  'emptyState.capabilities.mutate': 'Modificación',
  'activity.trace': 'Traza',
  'activity.copyTrace': 'Copiar traza',
  'activity.copyTraceSuccess': 'Traza copiada',
  'activity.live': 'En vivo',
  'activity.arguments': 'Argumentos',
  'activity.running': 'Ejecutando…',
  'activity.widgetInResponse': 'Widget mostrado en la respuesta de arriba',
  'activity.steps.waitingConfirmation': 'Esperando confirmación…',
  'activity.steps.waitingChoice': 'Esperando tu elección…',
  'activity.steps.suggestingReplies': 'Sugiriendo respuestas…',
  'activity.steps.running': 'Ejecutando {name}…',
  'activity.steps.failed': 'Error en {name}',
  'activity.steps.confirmationAnswered': 'Confirmación respondida',
  'activity.steps.choiceSubmitted': 'Elección enviada',
  'activity.steps.replySuggestionsShown': 'Sugerencias de respuesta mostradas',
  'activity.steps.ran': 'Se ejecutó {name}',
  'interactive.chooseOptions': 'Elegir opciones',
  'interactive.chooseOne': 'Elegir una opción',
  'interactive.choicesKeyboardHint': '1-9 · Enter · Esc',
  'interactive.confirmationKeyboardHint': 'Enter · Esc',
  'interactive.confirm': 'Confirmar',
  'interactive.confirmDeletion': 'Confirmar eliminación',
  'interactive.invalidArgs': 'Argumentos de herramienta interactiva no válidos',
  'replySuggestions.legend': 'Respuestas sugeridas',
  'replySuggestions.pickHint': 'para elegir · o escribe abajo',
  'replySuggestions.badges.model': 'Modelo',
  'replySuggestions.badges.status': 'Estado',
  'replySuggestions.badges.tools': 'Herramientas',
  'replySuggestions.badges.dataclass': 'Dataclass',
  'replySuggestions.badges.filter': 'Filtro',
  'scroll.toBottom': 'Ir al final',
  'errors.network.title': 'Conexión perdida',
  'errors.network.hintChat': 'Comprueba tu red o el endpoint del LLM e inténtalo de nuevo.',
  'errors.network.hintSuggestions': 'Comprueba tu conexión y los ajustes del LLM.',
  'errors.auth.title': 'Error de autenticación',
  'errors.auth.hint': 'Verifica tu clave API o credenciales en los ajustes del LLM.',
  'errors.timeout.title': 'Tiempo de espera agotado',
  'errors.timeout.hint':
    'El modelo tardó demasiado en responder. Inténtalo de nuevo en un momento.',
  'errors.rateLimit.title': 'Límite de velocidad alcanzado',
  'errors.rateLimit.hint': 'Espera unos segundos antes de enviar otra solicitud.',
  'errors.unknown.titleChat': 'Algo salió mal',
  'errors.unknown.titleSuggestions': 'No se pudieron cargar las sugerencias',
  'errors.unknown.hintChat': 'Inténtalo de nuevo o revisa los ajustes del LLM.',
  'errors.unknown.hintSuggestions': 'Regenera o comprueba la configuración del LLM.',
}

const enKeys = Object.keys(DEFAULT_ASSISTANT_LABELS) as (keyof typeof DEFAULT_ASSISTANT_LABELS)[]
for (const key of enKeys) {
  if (!fr[key]) fr[key] = DEFAULT_ASSISTANT_LABELS[key]
  if (!es[key]) es[key] = DEFAULT_ASSISTANT_LABELS[key]
}

mkdirSync('src/i18n/assistant-ui', { recursive: true })
const fmt = (obj: Record<string, string>) =>
  Object.entries(obj)
    .map(([k, v]) => `  '${k.replace(/'/g, "\\'")}': ${JSON.stringify(v)},`)
    .join('\n')

writeFileSync(
  'src/i18n/assistant-ui/fr.ts',
  `import type { AssistantLabelOverrides } from '@4djs/assistant'\n\nexport const frAssistantLabels: AssistantLabelOverrides = {\n${fmt(fr)}\n}\n`
)
writeFileSync(
  'src/i18n/assistant-ui/es.ts',
  `import type { AssistantLabelOverrides } from '@4djs/assistant'\n\nexport const esAssistantLabels: AssistantLabelOverrides = {\n${fmt(es)}\n}\n`
)
writeFileSync(
  'src/i18n/assistant-ui/index.ts',
  `import type { AssistantLabelOverrides } from '@4djs/assistant'\nimport type { Locale } from '../labels'\nimport { frAssistantLabels } from './fr'\nimport { esAssistantLabels } from './es'\n\nexport function getAssistantLabelOverrides(locale: Locale): AssistantLabelOverrides {\n  if (locale === 'fr') return frAssistantLabels\n  if (locale === 'es') return esAssistantLabels\n  return {}\n}\n`
)
console.log('Generated', enKeys.length, 'keys')
