import { cn } from '@4d/ui'

import brandMarkUrl from '../assets/brand-mark.svg?url'

type AppBrandIconProps = {
  className?: string
  /** Accessible name; omit for decorative use (`aria-hidden`). */
  title?: string
}

/**
 * App brand mark — OS-style squircle with the current branding art.
 * Generated by `bun run branding` from the icon-source SVG.
 * Full-bleed OS bundle icons stay unrounded (platform masks them).
 */
export function AppBrandIcon({ className, title }: AppBrandIconProps) {
  const label = title?.trim() || undefined
  const decorative = !label
  return (
    <img
      src={brandMarkUrl}
      alt={label ?? ''}
      aria-hidden={decorative ? true : undefined}
      className={cn('shrink-0 object-contain', className)}
      draggable={false}
    />
  )
}
