import { getEnvFaker } from '~/lib/env/dynamic'
import { resolveEnvString } from '~/lib/env/runtime'
import { proposeFieldTemplateKeys } from '~/lib/env/suggest-field-templates'
import { analyzableAttributes, isSystemEntityKey } from './helpers'
import type { EntityIoAttribute } from './types'

export type AnonymizeFieldMode = 'faker' | 'fixed' | 'keep' | 'empty'

export type AnonymizeFieldPlan = {
  name: string
  type?: string
  mode: AnonymizeFieldMode
  /** Template expression e.g. `{{$faker.person.firstName | lower}}`. */
  fakerKey?: string
  /** Literal replacement used when mode is fixed. */
  fixedValue?: string
}

/** Build a single default anonymization mapping for one attribute. */
export function buildAnonymizeFieldPlan(attr: EntityIoAttribute): AnonymizeFieldPlan {
  const keys = proposeFieldTemplateKeys({ name: attr.name, type: attr.type })
  const fakerKey = keys.find((k) => k.startsWith('$faker.')) ?? keys[0]
  if (fakerKey?.startsWith('$faker.') || fakerKey?.startsWith('$')) {
    return {
      name: attr.name,
      type: attr.type,
      mode: 'faker',
      fakerKey: `{{${fakerKey}}}`,
    }
  }
  const typeKey =
    attr.type === 'bool'
      ? '$faker.datatype.boolean'
      : attr.type === 'date'
        ? '$faker.date.past'
        : isNumericType(attr.type)
          ? '$faker.number.int'
          : '$faker.lorem.word'
  return { name: attr.name, type: attr.type, mode: 'faker', fakerKey: `{{${typeKey}}}` }
}

/** Attributes that can appear in the anonymize field plan. */
export function listAnonymizeMappableAttributes(
  attrs: EntityIoAttribute[],
  primaryKey?: string
): EntityIoAttribute[] {
  return analyzableAttributes(attrs).filter((a) => {
    if (primaryKey && a.name === primaryKey) return false
    if (a.autosequence || a.readOnly) return false
    return true
  })
}

/** Build default anonymization plan from schema attributes. */
export function buildDefaultAnonymizePlan(
  attrs: EntityIoAttribute[],
  primaryKey?: string
): AnonymizeFieldPlan[] {
  return listAnonymizeMappableAttributes(attrs, primaryKey).map(buildAnonymizeFieldPlan)
}

function isNumericType(type: string): boolean {
  return ['byte', 'word', 'long', 'long64', 'number', 'real', 'float', 'duration'].includes(
    type.toLowerCase()
  )
}

export type AnonymizeOptions = {
  plan: AnonymizeFieldPlan[]
  /** Optional Faker seed for reproducible dumps. */
  seed?: number
}

function coerceReplacement(original: unknown, replacement: string, fieldType?: string): unknown {
  if (typeof original === 'boolean' || fieldType?.toLowerCase() === 'bool') {
    const normalized = replacement.trim().toLowerCase()
    if (normalized === 'true' || normalized === '1') return true
    if (normalized === 'false' || normalized === '0') return false
  }
  if (typeof original === 'number' || (fieldType ? isNumericType(fieldType) : false)) {
    const number = Number(replacement)
    if (!Number.isNaN(number)) return number
  }
  return replacement
}

function asTemplate(expression: string): string {
  const trimmed = expression.trim()
  return trimmed.startsWith('{{') && trimmed.endsWith('}}') ? trimmed : `{{${trimmed}}}`
}

/** Apply anonymization plan to a single entity (returns a new object). */
export function anonymizeEntity(
  entity: Record<string, unknown>,
  options: AnonymizeOptions
): Record<string, unknown> {
  if (options.seed != null) {
    getEnvFaker().seed(options.seed)
  }

  const out: Record<string, unknown> = { ...entity }
  for (const field of options.plan) {
    if (!(field.name in out) && field.mode === 'keep') continue
    if (field.mode === 'keep') continue
    if (field.mode === 'empty') {
      out[field.name] = null
      continue
    }
    const original = entity[field.name]
    if (field.mode === 'fixed') {
      out[field.name] = coerceReplacement(original, field.fixedValue ?? '', field.type)
      continue
    }
    const key = field.fakerKey
    if (!key) {
      out[field.name] = null
      continue
    }
    // Resolve against the in-progress entity so plan entries can consume values
    // generated by earlier entries while untouched fields retain their source value.
    const resolved = resolveEnvString(asTemplate(key), { this: out })
    if (resolved.unresolved.length > 0) {
      out[field.name] = null
      continue
    }
    out[field.name] = coerceReplacement(original, resolved.text, field.type)
  }
  return out
}

/** Anonymize many entities. When seed is set, each row uses seed+index for uniqueness. */
export function anonymizeEntities(
  entities: Record<string, unknown>[],
  options: AnonymizeOptions
): Record<string, unknown>[] {
  return entities.map((entity, index) =>
    anonymizeEntity(entity, {
      plan: options.plan,
      seed: options.seed != null ? options.seed + index : undefined,
    })
  )
}

/** Keep optimistic-lock keys and only fields changed by the anonymization plan. */
export function prepareAnonymizedUpdate(
  entity: Record<string, unknown>,
  plan: AnonymizeFieldPlan[]
): Record<string, unknown> {
  const update: Record<string, unknown> = {
    __KEY: entity.__KEY,
    __STAMP: entity.__STAMP,
  }
  for (const field of plan) {
    if (field.mode !== 'keep') update[field.name] = entity[field.name]
  }
  return update
}

/**
 * Strip system + PK fields for create/download after anonymize.
 * When `plan` is provided, only mapped fields are kept (removed rows are omitted).
 */
export function stripForCreate(
  entity: Record<string, unknown>,
  primaryKey?: string,
  plan?: AnonymizeFieldPlan[]
): Record<string, unknown> {
  if (plan) {
    const out: Record<string, unknown> = {}
    for (const field of plan) {
      if (primaryKey && field.name === primaryKey) continue
      if (isSystemEntityKey(field.name)) continue
      out[field.name] = entity[field.name]
    }
    return out
  }

  const out: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(entity)) {
    if (isSystemEntityKey(key)) continue
    if (primaryKey && key === primaryKey) continue
    out[key] = value
  }
  return out
}
